using AGS.Types;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace AGS.Editor
{
    public class BuildTargetMacOS : BuildTargetBase
    {
        public const string MACOS_DIR = "macOS";
        public const string MACOS_PROJECT_DIR = "mygame";
        public const string MACOS_RESOURCES_DIR = "Resources";
        public const string MACOS_XCCONFIG_NAME = "mygame.xcconfig";

        private string GetEditorMacOSTemplateDir()
        {
            return Path.Combine(Factory.AGSEditor.EditorDirectory, MACOS_DIR);
        }

        /// <summary>
        /// A handful of files that must exist for the template to be usable.
        /// This is only a presence probe for IsAvailable and the "missing file"
        /// error - the whole template tree is copied recursively in Build(),
        /// not from this list, because AGSKit.xcframework alone is hundreds of
        /// files that would be impossible to keep enumerated here.
        /// </summary>
        public override IDictionary<string, string> GetRequiredLibraryPaths()
        {
            Dictionary<string, string> paths = new Dictionary<string, string>();
            string templateDir = GetEditorMacOSTemplateDir();
            // Frameworks ship as .zip archives (see osx-build.sh) so their
            // internal symlinks survive being copied here on Windows, so the
            // probe looks for the archives, not the unpacked frameworks.
            string[] probes =
            {
                Path.Combine("mygame.xcodeproj", "project.pbxproj"),
                MACOS_XCCONFIG_NAME,
                Path.Combine("Frameworks", "AGSKit.xcframework.zip"),
                Path.Combine("Frameworks", "SDL2.framework.zip"),
            };
            foreach (string probe in probes)
            {
                paths.Add(probe, templateDir);
            }
            return paths;
        }

        public override string[] GetPlatformStandardSubfolders()
        {
            return new string[]
            {
                GetCompiledPath(MACOS_PROJECT_DIR, MACOS_RESOURCES_DIR)
            };
        }

        public override void DeleteMainGameData(string name, CompileMessages errors)
        {
            string resourcesDir = Path.Combine(Path.Combine(OutputDirectoryFullPath, MACOS_PROJECT_DIR),
                MACOS_RESOURCES_DIR);
            DeleteCommonGameFiles(resourcesDir, name, errors);
        }

        /// <summary>
        /// Builds the xcconfig that carries the game's identity into Xcode.
        /// Written with UNIX line endings, since it is only ever read on macOS.
        /// </summary>
        public static string BuildXCConfigText(string productName, string bundleId, string version)
        {
            string text =
@"// Generated by the AGS Editor. Rebuilding the game overwrites this file, so
// set DEVELOPMENT_TEAM in Xcode's Signing & Capabilities tab instead of here,
// or keep your own copy of any edits.
PRODUCT_NAME = " + productName + @"
PRODUCT_BUNDLE_IDENTIFIER = " + bundleId + @"
MARKETING_VERSION = " + version + @"
CURRENT_PROJECT_VERSION = 1

DEVELOPMENT_TEAM =
";
            return text.Replace("\r\n", "\n");
        }

        /// <summary>
        /// Copies the whole template tree (project, frameworks, headers, icon
        /// set) into the compiled output, except the template's own Resources
        /// folder, which only holds a placeholder and is filled with game data
        /// afterwards.
        /// </summary>
        private void CopyTemplate(string templateDir, CompileMessages errors)
        {
            string resourcesPrefix = MACOS_RESOURCES_DIR + Path.DirectorySeparatorChar;
            foreach (string sourceFile in Directory.GetFiles(templateDir, "*", SearchOption.AllDirectories))
            {
                string relative = sourceFile.Substring(templateDir.Length).TrimStart(Path.DirectorySeparatorChar);
                if (relative.StartsWith(resourcesPrefix, StringComparison.OrdinalIgnoreCase))
                    continue; // don't copy the placeholder Resources content

                string destFile = GetCompiledPath(MACOS_PROJECT_DIR, relative);
                string destDir = Path.GetDirectoryName(Utilities.ResolveSourcePath(destFile));
                if (!Directory.Exists(destDir)) Directory.CreateDirectory(destDir);
                File.Copy(Utilities.ResolveSourcePath(sourceFile), Utilities.ResolveSourcePath(destFile), true);
            }
        }

        private void WarnAboutPlugins(CompileMessages errors)
        {
            foreach (Plugin plugin in Factory.AGSEditor.CurrentGame.Plugins)
            {
                errors.Add(new CompileWarning("macOS: plugin " + plugin.FileName +
                    " has no macOS build. Either add its sources to the exported Xcode project and register it " +
                    "in plugin_registration.cpp, or place a lib<name>.dylib in the app bundle and re-sign it with " +
                    "your own certificate."));
            }
        }

        public override bool Build(CompileMessages errors, bool forceRebuild)
        {
            if (!base.Build(errors, forceRebuild)) return false;
            WarnAboutPlugins(errors);

            CopyTemplate(GetEditorMacOSTemplateDir(), errors);

            string resourcesDir = GetCompiledPath(MACOS_PROJECT_DIR, MACOS_RESOURCES_DIR);
            if (!Directory.Exists(Utilities.ResolveSourcePath(resourcesDir)))
                Directory.CreateDirectory(Utilities.ResolveSourcePath(resourcesDir));

            foreach (string fileName in Directory.GetFiles(Path.Combine(AGSEditor.OUTPUT_DIRECTORY, AGSEditor.DATA_OUTPUT_DIRECTORY)))
            {
                if ((File.GetAttributes(fileName) & (FileAttributes.Hidden | FileAttributes.System | FileAttributes.Temporary)) != 0)
                    continue;
                if ((!fileName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)) &&
                    (!Path.GetFileName(fileName).Equals("winsetup.exe", StringComparison.OrdinalIgnoreCase)) &&
                    (!Path.GetFileName(fileName).Equals(AGSEditor.CONFIG_FILE_NAME, StringComparison.OrdinalIgnoreCase)))
                {
                    Utilities.HardlinkOrCopy(Path.Combine(resourcesDir, Path.GetFileName(fileName)), fileName, true);
                }
            }

            // Regenerate acsetup.cfg next to the game data, with the game's current parameters
            GenerateConfigFile(resourcesDir);

            // Overwrite the template xcconfig with the game's identity
            Settings settings = Factory.AGSEditor.CurrentGame.Settings;
            string xcconfig = BuildXCConfigText(settings.GameName, settings.MacOSBundleIdentifier, settings.MacOSAppVersion);
            string xcconfigPath = Utilities.ResolveSourcePath(GetCompiledPath(MACOS_PROJECT_DIR, MACOS_XCCONFIG_NAME));
            File.WriteAllBytes(xcconfigPath, Encoding.UTF8.GetBytes(xcconfig));

            errors.Add(new CompileWarning("macOS: Xcode project written to " +
                GetCompiledPath(MACOS_PROJECT_DIR) +
                ". Copy it to a Mac, open mygame.xcodeproj, choose your signing team, then Product > Archive."));
            return true;
        }

        public override string Name
        {
            get { return MACOS_DIR; }
        }

        public override string OutputDirectory
        {
            get { return MACOS_DIR; }
        }

        public override RuntimeSetup FixInvalidSettings(RuntimeSetup setup)
        {
            setup.GraphicsDriver = setup.GraphicsDriver == GraphicsDriver.D3D9 ? GraphicsDriver.OpenGL : setup.GraphicsDriver;

            return setup;
        }
    }
}
